### ISSUE TITLE
Raincloud errors: Error doing job: Future exception was never retrieved.

### ISSUE THREAD

**Issue by rockstar2020** [vanstinator/raincloudy#25]
Hello,
Recently my log file gets flooded with following error although raincloud sensors and switches seem to be working fine on hassio's dashboard.
Is there anything I can do to fix this?
Thanks a lot!

Log Details (ERROR)
Sun Jun 03 2018 18:26:25 GMT-0400 (Eastern Daylight Time)

Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/raincloud.py", line 118, in hub_refresh
    hass.data[DATA_RAINCLOUD].data.update()
  File "/usr/lib/python3.6/site-packages/raincloudy/core.py", line 119, in update
    self.controller.update()
  File "/usr/lib/python3.6/site-packages/raincloudy/controller.py", line 126, in update
    self._get_cu_and_fu_status()
  File "/usr/lib/python3.6/site-packages/raincloudy/controller.py", line 104, in _get_cu_and_fu_status
    req.raise_for_status()
  File "/usr/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: OK for url: https://wifiaquatimer.com/dajaxice/webserver.get_cu_and_fu_status/

**Comment by tchellomello** [comment]
Hello @mehdiheidari, how often are you getting this error? 500 error seems to be something on the server's side. I think we would need to get the full backtrace to get more info. 

I tested here on my end and worked fine. 

Are you easily able to reproduce it again?
