### ISSUE TITLE
raincloud in hass has stopped working

### ISSUE THREAD

**Issue by ghvader** [vanstinator/raincloudy#27]
any ideas on this? still works with the android app and from the web site. just can't get it to work in hass.

```
Thu Jul 12 2018 20:08:31 GMT-0400 (Eastern Daylight Time)

Error during setup of component raincloud
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/raincloudy/helpers.py", line 33, in serial_finder
    text=re.compile('controller_serial'))[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/setup.py", line 146, in _async_setup_component
    component.setup, hass, processed_config)  # type: ignore
  File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/raincloud.py", line 101, in setup
    raincloud = RainCloudy(username=username, password=password)
  File "/srv/homeassistant/lib/python3.5/site-packages/raincloudy/core.py", line 59, in __init__
    self.login()
  File "/srv/homeassistant/lib/python3.5/site-packages/raincloudy/core.py", line 68, in login
    self._authenticate()
  File "/srv/homeassistant/lib/python3.5/site-packages/raincloudy/core.py", line 99, in _authenticate
    parsed_controller = serial_finder(self.html['home'])
  File "/srv/homeassistant/lib/python3.5/site-packages/raincloudy/helpers.py", line 48, in serial_finder
    'Could not find any valid controller or faucet')
raincloudy.exceptions.RainCloudyException: Could not find any valid controller or faucet
```

**Comment by tchellomello** [comment]
Hello @ghvader , 

  If you follow the steps reported at https://github.com/tchellomello/raincloudy#usage, are you able to see the devices? 

 Thanks

**Comment by ghvader** [comment]
@tchellomello oops.. somehow a wrong password got into my config :(
working fine.

**Comment by tchellomello** [comment]
Thanks @ghvader :+1:
